### ISSUE TITLE
Setting Up Environment and Front-end Deployment

### ISSUE THREAD

**Issue by Martins-Ops** [MartOops/Sock_Shop_Proj#1]
The organization is currently focused on a venture involving a 8 multi-tier application. Each of these applications has been containerized using Docker, resulting in streamlined deployment and enhanced scalability.
**Task Assignment:**
- **Setup Environment**
- [x]  Clone the repository "Sock_Shop_Proj"
- [x]  Create a branch in the format "yourname_dev"
- [x]  Switch to the created branch
- [x] #2

- **Task on Kubernetes (k8s)**
- [x] Ensure that a cluster is up and running
- [x] Create a folder in the root dir martops/k8s/manifest/
- [x] Create a manifest for the following:
       - k8s Namespace with the name sock-shop-mops (save as sockshop-ns.yaml)
       - k8s _Deployment_ for the Front-end using the details (save as front-end.yaml)
          - name: front-end
          - namespace: sock-shop-mops
          - replicas: 3
          - image: weaveworksdemos/front-end:0.3.12
- [x] Apply the manifest and ensure state is running    
- [x] Push the manifest to your branch created earlier

Ensure that you mark the todo if done with the task, the Architecture of the Microservice is given below;
<img width="834" alt="Architecture" src="https://github.com/MartOops/Sock_Shop_Proj/assets/105437559/3c412d73-14d1-4db3-85ef-557473cd520f">
